# Generated by Django 2.1.7 on 2019-03-04 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='repository',
            name='description',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='repository',
            name='github_id',
            field=models.IntegerField(default=125549599, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='repository',
            name='url',
            field=models.CharField(default='https://github.com/dennys-bd/goals', max_length=255),
            preserve_default=False,
        ),
    ]
