# Generated by Django 2.1.7 on 2019-03-05 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='github_id',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
