# Generated by Django 2.1.7 on 2019-02-28 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='github_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
