# Generated by Django 2.1.7 on 2019-03-02 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_github_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='github_token',
        ),
        migrations.AddField(
            model_name='user',
            name='github_id',
            field=models.IntegerField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
