# Generated by Django 2.1.7 on 2019-03-10 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repositories', '0002_auto_20190306_0145'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commit',
            old_name='created_at',
            new_name='created',
        ),
    ]
