# Generated by Django 2.1.7 on 2019-03-13 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repositories', '0003_auto_20190310_0345'),
    ]

    operations = [
        migrations.AddField(
            model_name='repository',
            name='github_hook_id',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
